LINKS = {
  "FPU": [['Floating Point Unit', 'https://en.wikipedia.org/wiki/Floating-point_unit']],
  "VME": [['Virtual 8086 mode', 'https://en.wikipedia.org/wiki/Virtual_8086_mode#Virtual_8086_mode_enhancements_.28VME.29']],
  "DE": [['CR4.DE', 'https://en.wikipedia.org/wiki/Control_register#CR4']],
  "PSE": [['Page Size Extension.', 'http://en.wikipedia.org/wiki/Page_Size_Extension'], ['Page Directory Entries', 'https://en.wikipedia.org/wiki/Page_(computer_memory)']],
  "TSC": [['Time Stamp Counter.', 'http://en.wikipedia.org/wiki/Time_Stamp_Counter'], [ 'RDTSC', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "MSR": [['Model Specific Registers', 'http://en.wikipedia.org/wiki/Model-specific_register']],
  "PAE": [['Physical Address Extension', 'http://en.wikipedia.org/wiki/Physical_Address_Extension']],
  "MCE": [['Machine Check Exception', 'http://en.wikipedia.org/wiki/Machine_Check_Exception']],
  "CX8": [['CMPXCHG8B Instruction', 'http://www.felixcloutier.com/x86/CMPXCHG8B:CMPXCHG16B.html']],
  "APIC": [['Advanced Programmable Interrupt Controller', 'http://en.wikipedia.org/wiki/Advanced_Programmable_Interrupt_Controller']],
  "SEP": [['SYSENTER', 'http://www.felixcloutier.com/x86/SYSENTER.html'], ['SYSEXIT', 'http://www.felixcloutier.com/x86/SYSEXIT.html']],
  "MTRR": [['Memory Type Range Registers.', 'http://en.wikipedia.org/wiki/Memory_Type_Range_Registers']],
  "PGE": [['CR4.PGE', 'https://en.wikipedia.org/wiki/Translation_lookaside_buffer#Address_space_switch']],
  "MCA": [['Machine Check Architecture.', 'http://en.wikipedia.org/wiki/Machine_check_architecture']],
  "CMOV": [['Conditional Move Instructions.', 'http://www.rcollins.org/p6/opcodes/CMOV.html'], ['FCMOV', 'http://en.wikipedia.org/wiki/FCMOV']],
  "PAT": [['Page Attribute Table.', 'http://en.wikipedia.org/wiki/Page_Attribute_Table']],
  "PSE36": [['36-bit PSEs', 'http://en.wikipedia.org/wiki/PSE-36']],
  "PN": [['Processor serial number.', 'http://en.wikipedia.org/wiki/CPUID#EAX.3D3:_Processor_Serial_Number']],
  "CLFLUSH": [['CLFLUSH instruction.', 'https://en.wikipedia.org/wiki/CPU_cache#CACHE-LINES']],
  "DS": [],
  "ACPI": [['Thermal Monitor and Software Controlled Clock Facilities.', 'http://en.wikipedia.org/wiki/Advanced_Configuration_and_Power_Interface']],
  "MMX": [['Intel MMX Technology.', 'http://en.wikipedia.org/wiki/MMX_%28instruction_set%29']],
  "FXSR": [['CR4.OSFXSR', 'https://en.wikipedia.org/wiki/Control_register#CR4']],
  "XMM": [['SSE', 'http://en.wikipedia.org/wiki/Streaming_SIMD_Extensions']],
  "XMM2": [['SSE2', 'http://en.wikipedia.org/wiki/SSE2']],
  "SELFSNOOP": [['Self Snoop.', 'http://en.wikipedia.org/wiki/Cache_snooping']],
  "HT": [['Hyper-Threading.', 'http://en.wikipedia.org/wiki/Hyperthreading']],
  "ACC": [],
  "IA64": [['IA-64', 'http://en.wikipedia.org/wiki/IA-64']],
  "PBE": [['Pending Break Enable.', 'https://en.wikipedia.org/wiki/CPUID#EAX.3D1:_Processor_Info_and_Feature_Bits']],
  "SYSCALL": [['SYSCALL', 'http://www.felixcloutier.com/x86/SYSCALL.html'], ['SYSRET', 'http://www.felixcloutier.com/x86/SYSRET.html']],
  "MP": [['MP Capable.', 'https://en.wikipedia.org/wiki/Multiprocessing']],
  "NX": [['Execute Disable.', 'http://en.wikipedia.org/wiki/NX_bit']],
  "MMXEXT": [['MMX extensions.', 'http://en.wikipedia.org/wiki/MMX_%28instruction_set%29']],
  "FXSR_OPT": [],
  "GBPAGES": [['pages', 'https://en.wikipedia.org/wiki/Page_(computer_memory)']],
  "RDTSCP": [['RDTSCP.', 'http://www.felixcloutier.com/x86/RDTSCP.html']],
  "LM": [['Long Mode (x86-64).', 'https://en.wikipedia.org/wiki/Long_mode']],
  "3DNOWEXT": [['3DNow!', 'https://en.wikipedia.org/wiki/3DNow%21#3DNow_extensions']],
  "3DNOW": [['3DNow!.', 'http://en.wikipedia.org/wiki/3DNow%21']],
  "RECOVERY": [],
  "LONGRUN": [],
  "LRTI": [],
  "CXMMX": [['MMX extensions.', 'https://en.wikipedia.org/wiki/Extended_MMX']],
  "K6_MTRR": [['MTRRs.', 'https://en.wikipedia.org/wiki/Memory_type_range_register']],
  "CYRIX_ARR": [['MTRRs', 'https://en.wikipedia.org/wiki/Memory_type_range_register'], ['ARRs', 'https://en.wikipedia.org/wiki/Address-range_register']],
  "CENTAUR_MCR": [['MTRRs', 'https://en.wikipedia.org/wiki/Memory_type_range_register']],
  "K8": [],
  "K7": [],
  "P3": [],
  "P4": [],
  "CONSTANT_TSC": [['ticks', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter'], ['TSC', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "UP": [['smp kernel', 'https://en.wikipedia.org/wiki/Symmetric_multiprocessing']],
  "ART": [],
  "ARCH_PERFMON": [['Intel Architectural PerfMon.', 'http://www.intel.com/software/pcm']],
  "PEBS": [['Precise-Event Based Sampling.', 'https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol3/o_fe12b1e2a880e0ce-734.html']],
  "BTS": [['Branch Trace Store.', 'https://en.wikipedia.org/wiki/Branch_trace']],
  "SYSCALL32": [],
  "SYSENTER32": [],
  "REP_GOOD": [],
  "MFENCE_RDTSC": [['RDTSC.', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter'], ['(hidden by default)', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "LFENCE_RDTSC": [['RDTSC', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter'], ['(hidden by default)', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "ACC_POWER": [['Accumulated Power Mechanism.', 'https://lkml.org/lkml/2016/1/6/873']],
  "NOPL": [['The NOPL (0F 1F) instructions.', 'http://john.freml.in/amd64-nopl']],
  "ALWAYS": [],
  "XTOPOLOGY": [],
  "TSC_RELIABLE": [['TSC', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter'], ['reliable.', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "NONSTOP_TSC": [['TSC', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter'], ['does not stop', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "CPUID": [['CPU', 'http://x86.renejeschke.de/html/file_module_x86_id_45.html'], ['CPUID', 'https://en.wikipedia.org/wiki/CPUID']],
  "EXTD_APICID": [['extended APICID', 'https://software.intel.com/en-us/articles/intel-64-architecture-processor-topology-enumeration']],
  "AMD_DCM": [],
  "APERFMPERF": [['APERFMPERF.', 'https://lwn.net/Articles/283769/']],
  "NONSTOP_TSC_S3": [['TSC', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter'], ['doesn\'t stop', 'http://oliveryang.net/2015/09/pitfalls-of-TSC-usage/']],
  "TSC_KNOWN_FREQ": [['TSC', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter']],
  "XMM3": [['SSE3.', 'https://en.wikipedia.org/wiki/SSE3']],
  "PCLMULQDQ": [['instruction.', 'https://en.wikipedia.org/wiki/CLMUL_instruction_set'], ['PCLMULQDQ', 'http://www.felixcloutier.com/x86/PCLMULQDQ.html']],
  "DTES64": [],
  "MWAIT": [['Monitor/Mwait support.', 'http://en.wikipedia.org/wiki/SSE3#Intel_instructions']],
  "DSCPL": [],
  "VMX": [['Hardware virtualization.', 'http://en.wikipedia.org/wiki/X86_virtualization#Intel_virtualization_.28VT-x.29']],
  "SMX": [['Safer', 'http://en.wikipedia.org/wiki/Trusted_Execution_Technology'], ['mode.', 'http://en.wikipedia.org/wiki/Trusted_Platform_Module']],
  "EST": [['Intel SpeedStep', 'https://en.wikipedia.org/wiki/SpeedStep']],
  "TM2": [['Thermal Monitor 2.', 'http://en.wikipedia.org/wiki/Tm2']],
  "SSSE3": [['Supplemental SSE-3.', 'https://en.wikipedia.org/wiki/SSSE3']],
  "CID": [],
  "SDBG": [],
  "FMA": [['Fused multiply-add.', 'http://en.wikipedia.org/wiki/FMA_instruction_set']],
  "CX16": [['CMPXCHG16B.', 'https://en.wikipedia.org/wiki/Double_compare-and-swap']],
  "XTPR": [],
  "PDCM": [],
  "PCID": [],
  "DCA": [],
  "XMM4_1": [['SSE-4.1.', 'http://en.wikipedia.org/wiki/SSE4.1#SSE4.1']],
  "XMM4_2": [['SSE-4.2.', 'http://en.wikipedia.org/wiki/SSE4.2#SSE4.2']],
  "X2APIC": [['x2APIC.', 'http://en.wikipedia.org/wiki/X2APIC']],
  "MOVBE": [['instruction.', 'http://www.felixcloutier.com/x86/MOVBE.html'], ['MOVBE', 'https://en.wikipedia.org/wiki/Big-endian']],
  "POPCNT": [['POPCNT ', 'https://en.wikipedia.org/wiki/Popcnt'], ['instruction.', 'http://en.wikipedia.org/wiki/SSE4#POPCNT_and_LZCNT']],
  "TSC_DEADLINE_TIMER": [['Tsc', 'https://en.wikipedia.org/wiki/Time_Stamp_Counter']],
  "AES": [['AES instructions.', 'http://en.wikipedia.org/wiki/AES_instruction_set']],
  "XSAVE": [
          ['XSAVE', 'http://www.felixcloutier.com/x86/XSAVE.html'],
          ['XGETBV.', 'http://www.felixcloutier.com/x86/XGETBV.html'],
          ['XRSTOR', 'http://www.felixcloutier.com/x86/XRSTOR.html'],
          ['XSETBV', 'http://www.felixcloutier.com/x86/XSETBV.html']],
  "OSXSAVE": [['XSAVE', 'http://www.felixcloutier.com/x86/XSAVE.html']],
  "AVX": [['Advanced Vector Extensions.', 'http://en.wikipedia.org/wiki/Advanced_Vector_Extensions']],
  "F16C": [['fp conversions.', 'https://en.wikipedia.org/wiki/F16C'], ['16-bit', 'https://en.wikipedia.org/wiki/Half-precision']],
  "RDRAND": [['The RDRAND', 'http://en.wikipedia.org/wiki/RdRand'], ['instruction.', 'http://www.felixcloutier.com/x86/RDRAND.html']],
  "HYPERVISOR": [['hypervisor.', 'https://en.wikipedia.org/wiki/Hypervisor']],
  # NOW HERE
  "XSTORE": [['RNG present', 'https://en.wikipedia.org/wiki/Random_number_generation']],
  "XSTORE_EN": [['RNG enabled.', 'https://en.wikipedia.org/wiki/Random_number_generation']],
  "XCRYPT": [],
  "XCRYPT_EN": [],
  "ACE2": [],
  "ACE2_EN": [],
  "PHE": [],
  "PHE_EN": [],
  "PMM": [],
  "PMM_EN": [],
  "LAHF_LM": [['LAHF', 'http://x86.renejeschke.de/html/file_module_x86_id_148.html']],
  "CMP_LEGACY": [],
  "SVM": [['Secure virtual machine.', 'http://en.wikipedia.org/wiki/X86_virtualization#AMD_virtualization_.28AMD-V.29']],
  "EXTAPIC": [],
  "CR8_LEGACY": [],
  "ABM": [['Advanced bit manipulation.', 'https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#ABM_.28Advanced_Bit_Manipulation.29']],
  "SSE4A": [['SSE-4A.', 'http://en.wikipedia.org/wiki/SSE4#SSE4a']],
  "MISALIGNSSE": [],
  "3DNOWPREFETCH": [['3DNow', 'https://en.wikipedia.org/wiki/3DNow!']],
  "OSVW": [['OS Visible Workaround.', 'http://developer.amd.com/wordpress/media/2012/10/24593_APM_v21.pdf']],
  "IBS": [['Instruction Based Sampling.', 'https://en.wikipedia.org/wiki/Hardware_performance_counter#Instruction_based_sampling']],
  "XOP": [['extended AVX instructions.', 'http://en.wikipedia.org/wiki/XOP_instruction_set']],
  "SKINIT": [],
  "WDT": [['Watchdog timer.', 'https://en.wikipedia.org/wiki/Watchdog_timer']],
  "LWP": [['Profiling.', 'https://en.wikipedia.org/wiki/Profiling_(computer_programming)']],
  "FMA4": [['4 operands MAC instructions.', 'http://en.wikipedia.org/wiki/FMA_instruction_set']],
  "TCE": [],
  "NODEID_MSR": [],
  "TBM": [['bit manipulations.', 'https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#TBM']],
  "TOPOEXT": [],
  "PERFCTR_CORE": [],
  "PERFCTR_NB": [],
  "BPEXT": [],
  "PTSC": [],
  "PERFCTR_LLC": [],
  "MWAITX": [],
  "RING3MWAIT": [],
  "CPUID_FAULT": [],
  "CPB": [],
  "EPB": [],
  "CAT_L3": [],
  "CAT_L2": [],
  "CDP_L3": [],
  "HW_PSTATE": [],
  "PROC_FEEDBACK": [],
  "SME": [],
  "INTEL_PPIN": [],
  "INTEL_PT": [['Intel Processor Trace.', 'https://software.intel.com/en-us/blogs/2013/09/18/processor-tracing']],
  "AVX512_4VNNIW": [],
  "AVX512_4FMAPS": [],
  "MBA": [],
  "TPR_SHADOW": [],
  "VNMI": [],
  "FLEXPRIORITY": [],
  "EPT": [],
  "VPID": [],
  "VMMCALL": [],
  "XENPV": [],
  "FSGSBASE": [],
  "TSC_ADJUST": [],
  "BMI1": [],
  "HLE": [],
  "AVX2": [],
  "SMEP": [],
  "BMI2": [],
  "ERMS": [],
  "INVPCID": [],
  "RTM": [],
  "CQM": [],
  "MPX": [],
  "RDT_A": [],
  "AVX512F": [['AVX-512', 'https://en.wikipedia.org/wiki/AVX-512']],
  "AVX512DQ": [['AVX-512', 'https://en.wikipedia.org/wiki/AVX-512']],
  "RDSEED": [],
  "ADX": [],
  "SMAP": [],
  "AVX512IFMA": [],
  "CLFLUSHOPT": [],
  "CLWB": [],
  "AVX512PF": [['AVX-512', 'https://en.wikipedia.org/wiki/AVX-512']],
  "AVX512ER": [['AVX-512', 'https://en.wikipedia.org/wiki/AVX-512']],
  "AVX512CD": [['AVX-512', 'https://en.wikipedia.org/wiki/AVX-512']],
  "SHA_NI": [],
  "AVX512BW": [['AVX-512 BW', 'https://en.wikipedia.org/wiki/AVX-512#New_instructions_in_AVX-512_BW_and_DQ']],
  "AVX512VL": [['AVX-512', 'https://en.wikipedia.org/wiki/AVX-512']],
  "XSAVEOPT": [],
  "XSAVEC": [],
  "XGETBV1": [],
  "XSAVES": [],
  "CQM_LLC": [],
  "CQM_OCCUP_LLC": [],
  "CQM_MBM_TOTAL": [],
  "CQM_MBM_LOCAL": [],
  "CLZERO": [],
  "IRPERF": [],
  "DTHERM": [],
  "IDA": [],
  "ARAT": [],
  "PLN": [],
  "PTS": [],
  "HWP": [],
  "HWP_NOTIFY": [],
  "HWP_ACT_WINDOW": [],
  "HWP_EPP": [],
  "HWP_PKG_REQ": [],
  "NPT": [],
  "LBRV": [],
  "SVML": [],
  "NRIPS": [],
  "TSCRATEMSR": [],
  "VMCBCLEAN": [],
  "FLUSHBYASID": [],
  "DECODEASSISTS": [],
  "PAUSEFILTER": [],
  "PFTHRESHOLD": [],
  "AVIC": [],
  "V_VMSAVE_VMLOAD": [],
  "VGIF": [],
  "AVX512VBMI": [],
  "PKU": [],
  "OSPKE": [],
  "AVX512_VPOPCNTDQ": [],
  "LA57": [],
  "RDPID": [],
  "OVERFLOW_RECOV": [],
  "SUCCOR": [],
  "SMCA": [],
  "F00F": [],
  "FDIV": [],
  "COMA": [],
  "AMD_TLB_MMATCH": [],
  "AMD_APIC_C1E": [],
  "11AP": [],
  "FXSAVE_LEAK": [],
  "CLFLUSH_MONITOR": [],
  "SYSRET_SS_ATTRS": [],
  "ESPFIX": [],
  "NULL_SEG": [],
  "SWAPGS_FENCE": [],
  "MONITOR": [],
  "AMD_E400": []
}
